# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def load_initial_data(apps, schema_editor):
    from clean.fixtures.loaders import initial_data_loader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=60, null=True, blank=True)),
                ('name_last', models.CharField(max_length=60, null=True, blank=True)),
                ('phone', models.CharField(max_length=12, null=True, blank=True)),
                ('address', models.TextField(max_length=240, null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True, blank=True)),
                ('contact_id', models.IntegerField(default=None))
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True))
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('job_id', models.IntegerField()),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clean.Contact'),)

            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean.Job'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean.FeedbackLevel'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean.Technician'),
        ),
        migrations.RunPython(load_initial_data)
    ]
